server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: oss-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    nacos:
      server-addr: 192.168.56.2:8848 # nacos

logging:
  level:
    org.rednote: debug

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    packages-to-scan: org.rednote.oss.controller

# Oss配置
oss:
  type: 1 # 0：本地存储, 1：阿里云存储

# 本地文件上传路径
file:
  upload:
    path: xxxxxxxxxxxxxx

aliyun:
  oss:
    endpoint: xxxxxxxxxxxxxxxxxxxxxxxxxx
    access-key-id: xxxxxxxxxxxxxxxxxxxxx
    access-key-secret: xxxxxxxxxxxxxxxxx
    bucket-name: xxxxxxxxxxxxxxxxxxxxxxx