server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: oss-service
  cloud:
    nacos:
      server-addr: 192.168.56.2:8848 # nacos

logging:
  level:
    org.rednote: debug

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    packages-to-scan: org.rednote.oss.controller

# Oss配置
oss:
  type: 0 # 0：是本地存储

# 文件上传路径
file:
  upload:
    path: D:/study/dev/temp/