server:
  port: 8080
spring:
  application:
    name: RedNote
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rednote?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null # JSON?????????
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          # ???????????
          min-idle: 0
          # ???????????
          max-idle: 8
          # ????????????
          max-active: 8
          # #???????????????????????
          max-wait: -1ms

mybatis-plus:
  type-aliases-package: com.rednote.entity # ?????

logging:
  level:
    com.rednote: debug

springdoc:
  api-docs:
  enabled: true # ??/??API?????
  path: /v3/api-docs # ??API???????
  swagger-ui:
    path: /swagger-ui.html # ??Swagger UI?????
    disable-swagger-default-url: true
    display-request-duration: true # ????????
    packages-to-scan: org.rednote.controller # ???????