server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: RedNote
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rednote?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

mybatis-plus:
  type-aliases-package: org.rednote.domain.entity

logging:
  level:
    org.rednote: debug

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    packages-to-scan: org.rednote.controller

# Oss配置
oss:
  type: 0 # 0：是本地存储

# 文件上传路径
file:
  upload:
    path: D:/study/dev/temp/